site_name: voxel-engine-documentation
nav:
  - dev-side documentaion: 
    - About Project: dev-side/about.md
    - Logging Module: dev-side/logging.md
  - user-side documentaion: 
    - Getting Started: usr-side/begin.md
  
theme:
  name: terminal
  palette: dark