using System.IO;

namespace Editor.Models
{
    class ProjectTemplate
    {
        public ProjectMetadata projectMetadata { get; set; }

        public ProjectTemplate(ProjectMetadata projectMetadata)
        {
            this.projectMetadata = projectMetadata;
            SetupCmakeFile();
            SetupSourceFile();
            SetupResources();
        }

        public void SetupCmakeFile()
        {
            string cmakeFile = "CMakeLists.txt";
            string sourceDir = EditorConfig.SOURCE_DIRECTORY.Replace('\\', '/');
            string engineDir = EditorConfig.ENGINE_DIRECTORY.Replace('\\', '/');
            string voxelsDir = projectMetadata.Base.Replace('\\', '/');
            string cmakeData = $$"""
                # CMAKE FILE GENERATED BY VOXEL EDITOR
                cmake_minimum_required(VERSION 3.30     )
                set(PROJ_NAME "{{projectMetadata.Name}}")
                set(PROJ_LANG LANGUAGES CXX C           )
                set(PROJ_VERS VERSION "1.0.0"           )
                set(PROJ_DESC DESCRIPTION "{{projectMetadata.Description}}")
                
                project(${PROJ_NAME} ${PROJ_DESC} ${PROJ_LANG} ${PROJ_VERS})
                find_package(OpenGL REQUIRED)
                include(GoogleTest)

                set(CMAKE_CXX_STANDARD 23           )
                set(CMAKE_CXX_STANDARD_REQUIRED true)

                set(CMAKE_GTEST_INCLUDE_DIRECTORY   "{{sourceDir}}/submodules/GTest/include/gtest")
                set(CMAKE_GTEST_SOURCES_DIRECTORY   "{{sourceDir}}/submodules/GTest/src"          )
                set(CMAKE_GLFW__INCLUDE_DIRECTORY   "{{sourceDir}}/submodules/Glfw/include"       )
                set(CMAKE_GLAD__INCLUDE_DIRECTORY   "{{sourceDir}}/submodules/Glad/include"       )
                set(CMAKE_GLAD__SOURCES_DIRECTORY   "{{sourceDir}}/submodules/Glad/src"           )
                
                add_subdirectory({{sourceDir}}/submodules/Glfw  ${CMAKE_CURRENT_BINARY_DIR}/glfw_build)          
