# This workflow builds and deploys MkDocs documentation from core/docs/ using core/mkdocs.yml
# It uses GitHub Pages to host the static site

name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "master" ]  # Deploy only when pushing to master
  workflow_dispatch:        # Also allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs and Material theme
      run: |
        pip install mkdocs mkdocs-terminal

    - name: Build MkDocs site
      # The site will be built from core/docs using core/mkdocs.yml config
      run: mkdocs build --config-file core/mkdocs.yml --site-dir site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages  # Change if using a different branch
